
# madhushesharam/.github/.github/workflows/sample-init.yml@main" 
name: Sample Init Reference

on:
  workflow_call:
    inputs:
      MANDATORY_PARAM:
        description: "A recommended parameter"
        required: false
        default: "default-mandatory"
      OPTIONAL_PARAM:
        description: "An optional parameter"
        required: false
        default: "N/A"

jobs:
  print-runner-info:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Parameters
        run: |
          echo "MANDATORY_PARAM: ${{ inputs.MANDATORY_PARAM }}"
          echo "OPTIONAL_PARAM: ${{ inputs.OPTIONAL_PARAM }}"

      - name: Print Runner Hostname
        run: |
          echo "Hostname: $(hostname)"

      - name: Print Runner IP Address
        run: |
          IP=$(hostname -I | awk '{print $1}')
          echo "IP Address: $IP"
